controller_manager:
  ros__parameters:

    use_sim_time: true
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      
joint_state_broadcaster:
  ros__parameters:
    frame_id: chassis

diff_drive_base_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    publish_rate: 50.0
    
    left_wheel_names: ["axle_front_left"]
    right_wheel_names: ["axle_front_right"]

    wheel_separation: 0.6
    #wheels_per_side: 1  # actually 2, but both are controlled by 1 signal
    wheel_radius: 0.25

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    odom_frame_id: odom
    base_frame_id: chassis
    
    # pose_covariance_diagonal : [0.001, 0.001, 0.0, 0.0, 0.0, 0.01]
    # twist_covariance_diagonal: [0.001, 0.0, 0.0, 0.0, 0.0, 0.01]

    open_loop: false
    enable_odom_tf: true

    # cmd_vel_timeout: 0.5
    # publish_limited_velocity: true
    use_stamped_vel: false
    #velocity_rolling_window_size: 10

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    # linear.x.has_velocity_limits: true
    # linear.x.has_acceleration_limits: true
    # linear.x.max_velocity: 1.0
    # linear.x.min_velocity: -1.0
    # linear.x.max_acceleration: 1.0
    # linear.x.max_jerk: .NAN
    # linear.x.min_jerk: .NAN

    # angular.z.has_velocity_limits: true
    # angular.z.has_acceleration_limits: true
    # angular.z.max_velocity: 1.0
    # angular.z.min_velocity: -1.0
    # angular.z.max_acceleration: 1.0
    # angular.z.min_acceleration: -1.0
    # angular.z.max_jerk: .NAN
    # angular.z.min_jerk: .NAN

