car:
  # Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  

  # PID velocity controller
  joints_velocity_controller:
    type: effort_controllers/JointGroupVelocityController
    joints:
      - axle_front_right
      - axle_front_left
    axle_front_right:
      pid: {p: 1000.0, i: 0.1, d: 3.0}
    axle_front_left:
      pid: {p: 1000.0, i: 0.1, d: 3.0}

