rrbot:
  # Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  

  # PID velocity controller
  joints_velocity_controller:
    type: effort_controllers/JointGroupVelocityController
    joints:
      - axel_front_right
      - axel_front_left
      - axel_back_left
      - axel_back_right
    joint1:
      pid: {p: 1000.0, i: 0.1, d: 3.0}
    joint2:
      pid: {p: 1000.0, i: 0.1, d: 3.0}

