car:
  # Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

  # PID velocity controller
  joints_position_controller:
    type: effort_controllers/JointGroupPositionController
    joints:
      - axle_front_rightee
      - axle_front_leftee
    axle_front_rightee:
      pid: { p: 1000.0, i: 0.1, d: 3.0 }
    axle_front_leftee:
      pid: { p: 1000.0, i: 0.1, d: 3.0 }
